I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 59, in script call
    call bread
  File "game/doors.rpy", line 666, in script call
    call closed
  File "game/script.rpy", line 59, in script call
    call bread
  File "game/doors.rpy", line 666, in script call
    call closed
ScriptError: could not find label 'closed'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 59, in script call
    call bread
  File "game/doors.rpy", line 666, in script call
    call closed
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\ast.py", line 1436, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 59, in script call
    call bread
  File "game/doors.rpy", line 666, in script call
    call closed
  File "C:\Users\Declan\Downloads\dmodding\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'closed'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
I Gently Open the Door: Now with more door! 2.4.2
Thu Apr 22 16:21:41 2021
